clermontech/clermontech.github.com

- _posts/2015-04-27-5-bonnes-raisons-de-venir-a-la-djangocong-clermont-ferrand.md
> Add new blog post (djangocong)

- _posts/2015-09-17-3-claude-dioudonnat-capistrano3-le-deploiement-finger-in-the-nose.md
Add my slides about Capistrano.
> add claude's slides

- _posts/2016-01-19-3-julien-millau-applications-payantes-sur-le-playstore.md
Slides url for the talk "Applications Payantes sur le PlayStore"
> Add slides url

- _posts/2016-10-31-api-hour-23.md
> try a width of 100%

- _layouts/home.html
Add a link to the list on the landing page.  Also make the twitter
account visible here.
> Increase list visibility

- README.md
> update readme to allow remote connections on jekyll

- _layouts/home.html
* put the blog posts at the first place, set the limit to the last 3 posts
* put the talks after the api-hours list,  set the limit to the last 4 talks
> change the hompage block order

- _posts/2016-02-24-api-hour-19.md
- _posts/2016-03-01-2-kevin-gautreau-drupal-8-quoi-de-neuf.md
He does not use an accents on his name on neither his [website] nor his
[twitter account].
[website]: https://twitter.com/kgaut
[twitter account]: https://kgaut.net/
> Remove accents on Kevin's name

- api-hours/wishlist.md
> Clean the wishlist

- _posts/2017-03-09-api-hour-26.md
This change makes sponsor exposition great again.
> Move the sponsor section above the program section

- _posts/2018-01-16-api-hour-33.md
- _posts/2018-01-16-bertrand-pelletier-machine-learning.md
- _posts/2018-01-16-sebastien-binet-go-introduction.md
- _posts/2018-01-16-thomas-bailly-kesako-kantiq.md
- _posts/2018-01-16-vincent-vermersch-event-sourcing.md
Ajout de la page de l'APIHour#33 avec les sous pages pour les talks
> Add talks and page for AH33

- _posts/2018-04-16-api-hour-35.md
> Add AH35 page

- _posts/2018-06-01-api-hour-36.md
- _posts/2018-06-01-loic-bourg-debug-js.md
Added the text of Loic Bourg's talk
> Add details of AH36 Loic Bourg talk

- _posts/2018-10-03-hacktoberfest-2018.md
> add hacktoberfest sponsoring

- _posts/2018-10-03-hacktoberfest-2018.md
> Fix typo in hacktober fest blog post

- _posts/2018-03-04-api-hour-34.md
- _posts/2018-03-04-baptiste-Moreau-De-developpeur-a-startuppeur.md
- _posts/2018-03-04-matthieu-giraud-Comment-rechercher-dans-une-base-de-donnees-chiffrees.md
- _posts/2018-03-04-noel-Martignoni-data.gouv.fr.md
- _posts/2018-03-04-paul-pinault-l-eco-systeme-bitcoin.md
- _posts/2018-04-16-api-hour-35.md
- _posts/2018-04-16-aymeric-brisse-algorithmique-et-programmation-dynamique-rimes-en-ique.md
- _posts/2018-04-16-richard-degenne-les-claviers.md
- _posts/2018-04-16-vincent-rousseau-jeremie-picot-duniter-logiciel-pour-la-co-creation-d-une-crypto-monnaie-libre-et-equitable.md
- _posts/2018-06-01-api-hour-36.md
- _posts/2018-07-14-api-hour-37.md
- _posts/2018-07-14-claude-dioudonnat-terraform-centraliser-la-gestion-de-votre-infra.md
- _posts/2018-07-14-julien-maupetit-using-ansible-to-make-deployments-to-openShif-versatile.md
- _posts/2018-07-14-julien-pervillé-monitorer-avec-grafana-et-prometheus-sous-kubernetes.md
- _posts/2018-07-14-manuel-raynaud-yubikey-la-cle-manquante-a-votre-trousseau.md
> add missing talks

- _posts/2018-10-23-Alban-Baixas-PHP-en-2018.md
- _posts/2018-10-23-Cedric-Charriere-jam-des-volcans.md
- _posts/2018-10-23-Karim-Bogtob-Utiliser-le-MBTI-pour-mieux-comprendre-ses-collegues.md
- _posts/2018-10-23-Paul-Pinault-gerer-plutot-que-de-subir-ses-API.md
- _posts/2018-10-23-api-hour-38.md
Pages were generated using #139
> add AH 38 pages

- README.md
- _layouts/talk.html
- _posts/2018-01-16-api-hour-33.md
- _posts/2018-03-04-baptiste-Moreau-De-developpeur-a-startuppeur.md
- _posts/2018-03-04-matthieu-giraud-Comment-rechercher-dans-une-base-de-donnees-chiffrees.md
- _posts/2018-03-04-noel-Martignoni-data.gouv.fr.md
- _posts/2018-03-04-paul-pinault-l-eco-systeme-bitcoin.md
- _posts/2018-04-16-aymeric-brisse-algorithmique-et-programmation-dynamique-rimes-en-ique.md
- _posts/2018-04-16-richard-degenne-les-claviers.md
- _posts/2018-04-16-vincent-rousseau-jeremie-picot-duniter-logiciel-pour-la-co-creation-d-une-crypto-monnaie-libre-et-equitable.md
- _posts/2018-06-01-loic-bourg-debug-js.md
- _posts/2018-06-01-pascal-lafourcade-rgpd.md
- _posts/2018-06-01-sylvain-laurent-state-channel.md
- _posts/2018-06-01-vincent-vermersch-observable.md
- _posts/2018-07-14-claude-dioudonnat-terraform-centraliser-la-gestion-de-votre-infra.md
- _posts/2018-07-14-julien-maupetit-using-ansible-to-make-deployments-to-openShif-versatile.md
- _posts/2018-07-14-julien-pervillé-monitorer-avec-grafana-et-prometheus-sous-kubernetes.md
- _posts/2018-07-14-manuel-raynaud-yubikey-la-cle-manquante-a-votre-trousseau.md
On a talk page, we are now able to start a video at a given time. This will allow us to use the main API Hour video without splitting it.
> allow to start a youtube video at a given time

- .travis.yml
- _posts/2018-12-06-Yannick-Peroux-postgresql.md
- _posts/2018-12-06-korben-bug-bounty.md
- _posts/2019-01-15-api-hour-40.md
J'ai ajouté les 2 vidéos. Je dois encore passer le son pour la 3ième vidéo au speaker.
J'ai fixé aussi un problème d'URL dans la page de l'AH40.
A savoir il faut mettre la date courante dans le nom du fichier pas la date de l'AH sinon jekyll build pas les future page. Pour l'autoriser il faut ajouter l'option ``--future``
> Ah39 video

- _config.yml
Pour rendre un peux plus visible l'évènement.
> Add announcement for the little big event 1

- _layouts/layout.html
- association.md
> Contact + mise à jour bureau

- _posts/2019-10-23-Julien-Perville-Kapitan.md
- _posts/2019-10-23-api-hour-44.md
Add Julien's talk to replace Florian Busi's one
> Add AH44 Kapitan's talk by Julien Pervillé

- _posts/2021-03-11-pascal-lafourcade-mission-cryptographie.md
- _posts/2021-03-11-paul-amar-livecoding-fastapi.md
- _posts/2021-03-11-paul-pinault-helium.md
- _posts/2021-03-11-sylavin-desgrais-alpine.md
Ajout des vidéos de l'APIHour #47 sur les pages des speakers.
> Added #APIHour47 videos

- _includes/nav.html
- cowork.md
> EOL cowork offer

- _posts/2023-04-26-10eme-anniversaire.md
> blog post 10y

- _layouts/layout.html
Pour valider le lien vers le site depuis la page profil mastodon
> add mastodon rel=me

- _posts/2023-11-27-sebastien-forissier-outils-de-contribution-a-osm.md
- _posts/2024-01-22-alxandre-ruiz-k6-loadtest-et-non-regression.md
- _posts/2024-01-22-anthony-graignic-expatriation-quand-l-amour-et-la-tech-s-entremelent.md
- _posts/2024-01-22-aymeric-brisse-raft-plongee-au-coeur-des-algorithmes-de-consensus.md
- _posts/2024-03-28-kevin-beaugrand-utilisation-de-gpt-dans-le-code-applicatif.md
- _posts/2024-03-28-paul-pinault-depin.md
- _posts/2024-03-28-richard-degenne-la-verite-sur-les-monades.md
- _posts/2024-05-23-nicolas-torion-ficus-ui.md
- _posts/2024-05-23-pierre-tachoire-introduction-a-zig-comptime.md
Added videos for AH 57, 58, 59, 60 !
> added video links for AH 57,58,59,60

- _posts/2024-10-25-florian-forestier-upgrade-docker-swarm.md
- _posts/2024-10-25-loic-bourg-devenv.md
- _posts/2024-10-25-pascal-lafourcade-vote-electronique.md
- _posts/2025-02-04-anthony-graignic-identites-numeriques.md
- _posts/2025-02-04-paul-pinault-meshtastic.md
- _posts/2025-02-04-richard-degenne-tdd.md
- _posts/2025-02-26-manuel-raynaud-whisper-et-peertube.md
- _posts/2025-02-26-william-durand-firefox-ai-et-webextensions.md
- _posts/2025-03-05-jean-baptiste-penrath-typographie-web.md
- _posts/2025-03-25-charles-olivier-anclin-paiment-par-carte-et-vie-privee.md
- _posts/2025-03-25-noel-martignoni-ros2.md
- _posts/2025-03-25-romain-chapon-lois-de-la-tech.md
> Videos AH62,63,64,65
